### ISSUE TITLE
Share links break the energy count - they start string concatenating

### ISSUE THREAD

**Issue by nickretallack** [pokemon-masters-stuff/pokemon-masters-stuff.github.io#15]
Visit [a share link](https://pokemon-masters-stuff.github.io/?e=1&grid=02%2C03%2C04%2C05%2C00%2C01%2C38%2C36%2C40%2C17%2C19%2C13%2C34%2C15%2C37%2C41%2C06%2C20&o=738&p=Mew), then un-select a hex.  Instead of adding to your energy, it does a string concatenation.   Gotta cast it to a number first.

**Comment by pokemon-masters-stuff** [comment]
Just deployed an update to fix this. Thanks for bringing it to our attention!
