### ISSUE TITLE
Feature Request: Add Pokemon's moves on-screen somewhere

### ISSUE THREAD

**Issue by benanderson1** [pokemon-masters-stuff/pokemon-masters-stuff.github.io#17]
Hey guys,

Reddit user here. I have used your site since your first announcement and it's awesome. I realized recently that with all these new grids being added, it would be helpful if I could see the pokemon's moves and power (default level) somewhere on screen. Something as a reference point to compare and decide if "inser newest sync pair" is good or not.

Let me know if you guys need help figuring this out and I can try to add it myself if necessary.

**Comment by pokemon-masters-stuff** [comment]
Hey! Thanks for reaching out to us. I think that's a great idea. I've personally been thinking about adding a bulk calculator but never got the time to do it, and I think your idea is better. Are you familiar with React? I can add you as a contributor. We can chat on Reddit or Discord too. My reddit username is u/endurance12916, and my Discord id is Zx#5660.
