### ISSUE TITLE
Sync Grid Helper in French

### ISSUE THREAD

**Issue by EternalStay** [pokemon-masters-stuff/pokemon-masters-stuff.github.io#18]
Hello !

I am French, so I suggest a different version of the pokemon-masters-stuff.github.io/src/utils/translations.js file with a better translation for French texts.

https://pastebin.com/XmRuJ9kE

Thank you !

(I don't really use Github, so I don't know how to suggest these changes. So I posted here.)

**Comment by pokemon-masters-stuff** [comment]
Thanks a lot for your help! I'll push your update later today.
