### ISSUE TITLE
[Feat Request] Synchronization between devices

### ISSUE THREAD

**Issue by ItachiSan** [pokemon-masters-stuff/pokemon-masters-stuff.github.io#19]
Hey, first issue here.
I have to say that the tool is amazing and has become more and more important in my daily approach to Pokémon Masters.

Feel free to ask questions about the issue, I would gladly fill up holes and give suggestions 😄 

So, here we go:

## Issue
Data is bound to a specific device where the user logs in.

## Expected
Wherever I log in, I should be able to see my grids.

## Additional thoughs
I believe that this should happen already, due to:
https://github.com/pokemon-masters-stuff/pokemon-masters-stuff.github.io/blob/source/src/actions/actionCreators.js#L285
If not, the method could be extended to support *creatorId* or similar.

**Comment by pokemon-masters-stuff** [comment]
Hi, thanks very much for reaching out! The logics for Save and Load features were written before we had a database so they had to rely on local storage. Now that we have a database it sure would be nice to store the save files there. However, currently I'm the only person working on this project and I'm prioritizing some other features. I'll put this on my to-do list and will probably get around to it some time in the future.

**Comment by ItachiSan** [comment]
Understood that! Let me know if I can help anyhow. 😄

**Comment by pokemon-masters-stuff** [comment]
Thanks! Let me think about what needs to be added. I'll get back to you in a few days. By any chance are you familiar with MongoDB and Express? If not no worries I should be able to write the backend.

**Comment by ItachiSan** [comment]
I know Mongo, Node.js ish.
I can definetely JavaScript, but will need a few tries before the code is good 😄

**Comment by pokemon-masters-stuff** [comment]
That's great! Truth be told I'm an amateur programmer so your code is probably a lot better than mine :). 

The website uses Google Cloud Functions (part of Firebase) to host backend logics and uses MongoDB to store data. I'll send you an invite to the backend code. I think we'll need to add a new Schema under `functions/models`, and some new routes under `functions/routes`. 

We should probably discuss whether to migrate the local save files to the server, and how to make sure unregistered users don't lose their saves. Do you use Slack by any chance?

**Comment by ItachiSan** [comment]
I may be a decent programmer, but not so much in JavaScript 😛 

Saw and accepted the invitation the invitation!

Regarding Slack, I do; I use the email available from my profile.

**Comment by pokemon-masters-stuff** [comment]
I invited you to a Slack channel a couple days ago using this email address: giovannisantini93@yahoo.it but I just noticed a message that says you haven't created an account yet. Should I be using another email?

**Comment by ItachiSan** [comment]
Hey, no, the email was correct!
I just had lots to do during the weekend 😝 
I just accepted 😄

**Comment by ItachiSan** [comment]
Hi @pokemon-masters-stuff & @zixing-li !
Hope you're fine, I've tried to ping you on Slack with no success.

I've a fully set-up local development environment ready to go and I checked the code for the front-end.

My best guess is, for implementing online synchronization:
1.  Rework the code here:
    * https://github.com/pokemon-masters-stuff/pokemon-masters-stuff.github.io/blob/source/src/components/SaveBuildButton/Desktop.js#L24
    * https://github.com/pokemon-masters-stuff/pokemon-masters-stuff.github.io/blob/source/src/containers/MobileLayout/index.js#L105
    so that the builds are stored remotely and not in local storage
2. *OPTIONAL* Improve the builds in the backend to not store redundant data

**Comment by pokemon-masters-stuff** [comment]
Hey, thanks for the message! Sorry I haven't logged on to Slack for a while. I'll chat with you there.
