### ISSUE TITLE
A user should be able to reset its password

### ISSUE THREAD

**Issue by ItachiSan** [pokemon-masters-stuff/pokemon-masters-stuff.github.io#20]
As in title.

A user that forgets it's password has no chance to reset it.

This issue is created in order to:
* discuss if it's relevant
* how to tackle the issue
* implementation process

Although I am not a dev for this project, I am suggesting this. Feedback is more than welcome! 😄

**Comment by pokemon-masters-stuff** [comment]
Thanks. In fact one user did send me a feedback about forgetting his password. I'll keep it on the to-do-list. I'll get back to you tomorrow about the other issue.

**Comment by ItachiSan** [comment]
Sounds lovely! 😄
