### ISSUE TITLE
Tier Lists

### ISSUE THREAD

**Issue by glennfu** [pokemon-masters-stuff/pokemon-masters-stuff.github.io#27]
After using [Spark's Tier List](https://docs.google.com/document/d/1vF42uzF-xpkcfIU2gVEY4Dl7sS_I3ITj8g5X2lo1usA/edit) I got to thinking about how a web app could really give it a boost to usability. I've been considering building my own app (I'm a Rails developer) and then I thought it would make much more sense to simply build on the awesome framework here.

1. Tier List Builder - I think the easiest ux would be to first have 5 input fields to give a name to 5 different tiers. Second, a dropdown for each Sync Pair to assign a tier (or skip that pokemon). Or maybe there's even a tier-list plugin for React.
2. View a Tier List - it can be displayed just like Spark's graphic. Then the power would be in being able to hover/click on the icons to see their names and link directly to popular builds for that Pair. Additionally, being able to have a search/filter controls would be great. Right now if I get a new pokemon in my roster, then go to see Spark's list, it takes me way too long to search the tiny squares back and forth and try to figure out where on the list is the pokemon I'm looking for. If I could just type "Syc" and instantly see Sycamore & Xerneas's icon light up, I'd know where he stands.
3. Rosters - If I could track my roster, it could provide benefits throughout the app. On Tier Lists, click a button like "filter by your roster" and all of the pairs that I actually own would highlight. Additionally you could filter by role to quickly find "who are my top rated Strikers in my roster". Rosters could also give immediate access to quick actions like "show popular builds for this Pair" or "show popular teams using this Pair". Or even better, what if I want to search for Teams with tag "Battle Villa" but only show results where all 3 Pairs are in my Roster.
4. Automatically generated Tier Lists - You already have such great data in the application. How about generating a Tier List based on tags? Say, I want to see a Champion Station Tier List. Click that, and you can aggregate the number of times (perhaps scaled by Likes) a Pair is included on Team Builds, and rank them accordingly. This would give a community powered view into which Pairs are providing the most value in a particular area of the game.

I'd love to see these features, and I'm willing to help, but unfortunately I barely have any React experience. If anyone already contributing here sees value in any of these ideas, they likely could implement them 100x faster than me. I thought I'd share my thoughts here before I start going too far on my own.

**Comment by zixing-li** [comment]
Hey Glenn, thanks for posting these suggestions! I saw your discord messages too so I'll chat with you there.
