### ISSUE TITLE
Switching pokemon doesn't reset grids

### ISSUE THREAD

**Issue by pokemon-masters-stuff** [pokemon-masters-stuff/pokemon-masters-stuff.github.io#3]
Just noticed a bug - if you select some grids and then switch to another Pokemon, the grids still remain selected. I think the issue is that "isSelected" is a local state in GridMap and it's not updated by the SelectPokemonDropdown component.

**Comment by gervjo** [comment]
I think I managed to fix it with this [commit](https://github.com/pokemon-masters-stuff/pokemon-masters-stuff.github.io/commit/d94a156ea8ccd26a2874cdf37e5616717bcc0a53)

**Comment by pokemon-masters-stuff** [comment]
Man you're awesome!

**Comment by gervjo** [comment]
Call it team work! 
Sorry for introducing this bug in the first place. I will be more careful in the future.

**Comment by pokemon-masters-stuff** [comment]
Thanks man! I just updated the colors for the grids. I think they look great now. Hope you like them.

Also, I installed Google Analytics yesterday and I can add you as a user. Do you have a preferred email address for this?

**Comment by gervjo** [comment]
Much more vivid, much better! Good job!
