### ISSUE TITLE
Missing Updated/New Sync Pairs.

### ISSUE THREAD

**Issue by elrod829** [pokemon-masters-stuff/pokemon-masters-stuff.github.io#34]
Other than the missing and updated pairs, there is no longer a one character name per team restriction

Currently Missing (That I know of off the top of my head):
---BP Rewards---
Hero & Mespirit
Nita & Landorus
Sophacles & Alolan Golem
Clemont & Magneton
Erika & Tangela
Candice & Froslass
Janine & Crobat

---Fair Scout Pairs---
Lana (Sygna Suit) & Tapu Lele
Hau (Sygna Suit) & Tapu Koko
Mina (Sygna Suit) & Tapu Fini
Acerola (Sygna Suit) & Tapu Bulu
Bruno & Onix
Lorelei & Cloyster
Lance & Dragonair
Agatha & Arbok
Calem (Champion) & (Shiny) Greninja
Serena (Champion) & Greninja

---Trainer Lodge Reward Pairs---
Lillie & Comfey
Marnie & Toxicroak
Steven & Cradily
Acerola & Banette
Serena & Fletchling
Cynthia & Gastrodon
Dawn & Wormadam
Gloria & Thwackey
Blue & Exeggutor
Professor Sycamore & Bulbasaur
Elesa & Joltik
May & Wailmer
Silver & Feraligatr
Rosa & Dewott
N & Sigilyph
Morty & Gastly
Raihan & Gigalith

---Non Fair Pairs---
Aaron & Vespiquen
Bertha & Hippowdon
Lucian & Girafarig
Blaine & Rapidash
Gordie & Coalossal
Melanie & Lapras
Agatha & Gengar
Lorelei & Lapras

---Event Pairs---
Helena (Hex Maniac) & Haunter
Kali (Furisode Girl) & Azumarill
Naomi (Sightseer) & Sandslash
Jessie & Arbok
James & Weezing
Bugsy & Beedrill

**Comment by VoltageMiner** [comment]
This project is no longer being updated or maintained. I would recommend you use [PoMaTools](https://ng-pomatools.web.app/) instead.
