### ISSUE TITLE
Skill information not showing up after opening the `ActiveSkillList`

### ISSUE THREAD

**Issue by gervjo** [pokemon-masters-stuff/pokemon-masters-stuff.github.io#8]
After opening the `ActiveSkillList`, the first hex to be clicked doesn't trigger the `SkillOverview` to be rendered. Although, once a second hex is clicked, the behaviour goes on as expected.

**Comment by gnbezerra** [comment]
It has to do with mouseEnter behavior on mobile.

If you close a `Drawer` or `SwipeableDrawer` (can be `Navigation` as well) and right after that tap on a hex, it doesn't trigger the mouseEnter event. However if you close the drawer, tap anywhere else on the page (any empty space) and then on a hex, it triggers mouseEnter and then `SkillOverview` shows up for the first hex.

Edit: I still don't know how to solve this, just updating with my findings.

**Comment by pokemon-masters-stuff** [comment]
Thank you for the insight!
